#[doc(hidden)]
pub use inventory;
pub use tyzen_macro::{Event, Type, command};
pub mod utils;

use crate::utils::snake_to_camel;

pub mod ts_type;

pub struct CommandMeta {
    pub name: &'static str,
    pub params: &'static [(&'static str, fn() -> String)],
    pub return_type: fn() -> String,
}

pub struct TypeMeta {
    pub name: &'static str,
    pub ts_def: fn() -> String,
}

pub struct EventMeta {
    pub name: &'static str,
    pub payload_type: fn() -> String,
}

pub trait TsType {
    fn ts_name() -> String;
}

inventory::collect!(CommandMeta);
inventory::collect!(TypeMeta);
inventory::collect!(EventMeta);

pub fn generate(output_path: &str) {
    generate_full(output_path, write_command_declarations, |_| {});
}

pub fn generate_with_commands(output_path: &str, write_commands: fn(&mut String)) {
    generate_full(output_path, write_commands, |_| {});
}

pub fn generate_full(
    output_path: &str,
    write_before_types: impl FnOnce(&mut String),
    write_after_types: impl FnOnce(&mut String),
) {
    use std::fs;
    use std::path::PathBuf;

    let path = PathBuf::from(output_path);
    fs::create_dir_all(path.parent().unwrap()).unwrap();

    let mut ts = String::new();
    ts.push_str("// auto-generated by tyzen, do not edit\n");
    ts.push_str("/** autogen commands **/\n");
    write_before_types(&mut ts);

    ts.push_str("\n/** autogen types **/\n");
    for t in inventory::iter::<TypeMeta> {
        ts.push_str(&(t.ts_def)());
        ts.push_str("\n");
    }

    ts.push_str("\n");
    ts.push_str("export type Result<T, E> = { status: \"ok\"; data: T } | { status: \"error\"; error: E }\n");

    write_after_types(&mut ts);

    let current_content = fs::read_to_string(&path).ok();
    if current_content.as_ref() != Some(&ts) {
        fs::write(&path, ts).unwrap();
        println!(
            "\x1b[32m\x1b[1m{:>12}\x1b[0m bindings updated -> \x1b[90m{}\x1b[0m",
            "Tyzen", output_path
        );
    } else {
        println!(
            "\x1b[33m\x1b[1m{:>12}\x1b[0m bindings are up to date",
            "Tyzen"
        );
    }
}

pub fn write_command_declarations(ts: &mut String) {
    ts.push_str("export type Commands = {\n");
    for cmd in inventory::iter::<CommandMeta> {
        let fn_name = snake_to_camel(cmd.name);
        let params_ts: Vec<String> = cmd
            .params
            .iter()
            .map(|(name, ty_fn)| format!("{}: {}", name, ty_fn()))
            .collect();

        ts.push_str(&format!(
            "  {}({}): Promise<{}>\n",
            fn_name,
            params_ts.join(", "),
            (cmd.return_type)(),
        ));
    }
    ts.push_str("}\n");
}
